# Generated by Django 5.0.3 on 2024-03-06 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_currency_user_delete_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='base_currency',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='currency_to',
        ),
    ]
