# Generated by Django 5.0.3 on 2024-03-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_currency_amount_remove_currency_base_currency_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
